In [21]:
import pandas as pd

citations_df = pd.read_csv("../data/processed/citations.csv")

citations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265726 entries, 0 to 265725
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   paper_id              265726 non-null  int64
 1   raw                   265644 non-null  object
 2   sentence              265726 non-null  object
 3   paragraph             265726 non-null  object
 4   co_cited_count        265726 non-null  int64
 5   section_id            259027 non-null  object
 6   paragraph_id          265684 non-null  object
 7   sentence_id           265726 non-null  object
 8   sentence_seq_number   265726 non-null  int64
 9   reference_seq_number  265726 non-null  int64
 10  author                227628 non-null  object
 11  page                  74403 non-null   float64
 12  year                  222883 non-null  float64
 13  title                 265726 non-null  object
 14  filename              265726 non-null  object
 15  sentence_count        265726 non-null  int64
 16  reference_count       265726 non-null  int64
 17  source title          237907 non-null  object
 18  similarity            265726 non-null  float64
 19  sentence_keywords     265726 non-null  object
 20  paragraph_keywords    265726 non-null  object
dtypes: float64(3), int64(6), object(12)
memory usage: 42.6+ MB

In [22]:
citations_df.head()

,paper_id,raw,sentence,paragraph,co_cited_count,section_id,paragraph_id,sentence_id,sentence_seq_number,reference_seq_number,...,page,year,title,filename,sentence_count,reference_count,source title,similarity,sentence_keywords,paragraph_keywords
0,1,Streissler (1972),"In particular, as the classic contributions of...",This chapter delineates the nature of the Aust...,0,_gzuY8cP,_NwgSU35,_TMX2wdg,4,1,...,NaN,1972.0,Unknown Title,10.1002.9780470999059.ch17.pdf.grobid.tei.xml,298,20,Review of Austrian Economics,44.444444,['subjectivism'],"['austrian', 'marginalist revolution', 'carl m..."
1,1,"(Menger, [1981] 1871, p. 49)",The final two paragraphs of the preface are a ...,The distinctly Austrian strand of the marginal...,1,_NytzfyY,_Z99Bvn5,_aJz9uAb,10,2,...,49.0,1981.0,Unknown Title,10.1002.9780470999059.ch17.pdf.grobid.tei.xml,298,20,Review of Austrian Economics,44.444444,['menger'],"['austrian', 'marginalist revolution', 'carl m..."
2,1,"1871, p. 49)",The final two paragraphs of the preface are a ...,The distinctly Austrian strand of the marginal...,1,_NytzfyY,_Z99Bvn5,_aJz9uAb,10,3,...,49.0,1871.0,Unknown Title,10.1002.9780470999059.ch17.pdf.grobid.tei.xml,298,20,Review of Austrian Economics,44.444444,['menger'],"['austrian', 'marginalist revolution', 'carl m..."
3,1,"(Menger, [1981] 1871, p. 48)",He also goes to some length in the preface to ...,The distinctly Austrian strand of the marginal...,0,_NytzfyY,_Z99Bvn5,_54sgkMV,11,4,...,48.0,1981.0,Unknown Title,10.1002.9780470999059.ch17.pdf.grobid.tei.xml,298,20,Review of Austrian Economics,44.444444,['menger'],"['austrian', 'marginalist revolution', 'carl m..."
4,1,Menger's (1985Menger's ( [1883] ] ),A detour into Menger's (1985Menger's ( [1883] ...,"What would such a reform mean, particularly if...",0,_NytzfyY,_ZYekVnE,_F7mv66u,16,5,...,NaN,1883.0,Unknown Title,10.1002.9780470999059.ch17.pdf.grobid.tei.xml,298,20,Review of Austrian Economics,44.444444,"['menger', 'methodology']","['historicism', 'menger', 'economics', 'method..."

In [23]:
citations_df['author'].value_counts().head(10)

author
Mises         7754
Hayek         6281
Kirzner       3013
Rothbard      2647
Schumpeter    1992
Boettke       1629
Buchanan      1485
Smith         1404
Menger        1290
Foss          1289
Name: count, dtype: int64

In [24]:
mises_citations_df = citations_df[citations_df.author == 'Mises'].sort_values(by='page')

mises_citations_df.head(10)

,paper_id,raw,sentence,paragraph,co_cited_count,section_id,paragraph_id,sentence_id,sentence_seq_number,reference_seq_number,...,page,year,title,filename,sentence_count,reference_count,source title,similarity,sentence_keywords,paragraph_keywords
95362,834,"(Mises, 1996(Mises, [1949]], p. 1)",The practitioners of methodological holism are...,One of the defining characteristics of Austria...,0,_4dGvzna,_97b4QYq,_dz5ekbM,96,47,...,1.0,1949.0,AN AUSTRIAN APPROACH TO CLASS STRUCTURE,10.1108.S1529-213420150000019009.pdf.grobid.te...,367,43,Advances in Austrian Economics,100.000000,['NO-MATCH'],"['austrian', 'economics', 'methodological indi..."
196231,1842,"(Mises 2011, 1)","Interventionism, for its part, ""seeks to retai...",Consider Mises's own definitions of capitalism...,0,_yCU3SGE,_h8VDttU,_5k2NTcp,352,148,...,1.0,2011.0,Is the Austrian School Value-Free? On the Depe...,IS-THE-AUSTRIAN-SCHOOL-VALUEFREE-ON-THE-DEPEND...,458,87,Quarterly Journal of Austrian Economics,100.000000,"['interventionism', 'private property', 'produ...","['capitalism', 'socialism', 'interventionism',..."
132474,1197,Mises (1944: 1-19),"Indeed, Mises (1944: 1-19) explicitly cites th...",Democracy was dangerous because it enabled the...,0,_ThHCvKg,_xKvBxdX,_EndqMMB,3399,1633,...,1.0,1944.0,THE DARK SIDE OF MANAGEMENT,10.4324.9781315754581.pdf.grobid.tei.xml,3855,337,Knowledge Management and Organizational Learning,76.923077,['NO-MATCH'],"['democracy', 'economy', 'neo-liberalism', 'th..."
132511,1197,"Mises, 1944: 1-19)","(Lippmann, 1938(Lippmann, /1943: 263;: 263; em...",The kind of self-education which a self-govern...,3,_W7w3J4K,_FXcX2C6,_mpaD3bx,3456,1675,...,1.0,1944.0,THE DARK SIDE OF MANAGEMENT,10.4324.9781315754581.pdf.grobid.tei.xml,3855,337,Knowledge Management and Organizational Learning,76.923077,['NO-MATCH'],"['education', 'words', 'democracy', 'discovery..."
202393,1920,"Mises's (1962, 1)","Indeed, the logical structure of the human min...","That is to say, Mises believes that I can gras...",0,_JRV4vR4,_K4EEPwH,_kzagVzN,367,282,...,1.0,1962.0,Ludwig von Mises on the epistemological founda...,Ludwig-von-Mises-on-the-epistemological-founda...,533,66,Review of Austrian Economics,100.000000,"['structure', 'epistemology', 'knowledge', 'po...","['action', 'structure', 'epistemology', 'knowl..."
156079,1392,"Mises (2011, 1-44)","In a world of national fiat currencies, a bala...",An example contrasting balance of payments mov...,0,_GTA3FR2,_j2yjvbt,_QhFwbBe,63,16,...,1.0,2011.0,Austrian Monetary Theory: Comment on Pascal Sa...,Austrian-Monetary-Theory-Comment-on-Pascal-Sal...,91,22,Quarterly Journal of Austrian Economics,98.245614,['fiat currencies'],"['fiat currencies', 'money', 'policy', ""gresha..."
27884,90,"( Mises, [1949] 2008, pp.1)",The centerpiece of the Austrian school is the ...,The centerpiece of the Austrian school is the ...,0,_q27W6tg,_KvWq5aw,_jCjH8qA,21,9,...,1.0,1949.0,Unknown Title,10.1007.978-3-658-07077-9.pdf.grobid.tei.xml,1435,52,Review of Austrian Economics,44.444444,"['the austrian school', 'human action', 'praxe...","['the austrian school', 'human action', 'praxe..."
41267,237,"Mises's (1962, 1)","Indeed, the logical structure of the human min...","That is to say, Mises believes that I can gras...",0,_3gaD7Wa,_4sGu8jS,_X2R8mvd,367,282,...,1.0,1962.0,Ludwig von Mises on the epistemological founda...,10.1007.s11138-008-0046-4.pdf.grobid.tei.xml,533,66,Review of Austrian Economics,100.000000,"['structure', 'epistemology', 'knowledge', 'po...","['action', 'structure', 'epistemology', 'knowl..."
202918,1925,"Mises (1928, 1, 3, 41-42)",In his 1928 publication Geldwertstabilisierung...,In his 1928 publication Geldwertstabilisierung...,0,_zn378vU,_kd2BNYB,_qyXMvmc,92,29,...,1.0,1928.0,Ludwig von Mises's Outstanding Position in Eco...,Ludwig-von-Misess-Outstanding-Position-in-Econ...,327,30,Quarterly Journal of Austrian Economics,98.333333,"['money', 'credit', 'trade', 'monetary policy']","['money', 'credit', 'trade', 'monetary policy'..."
116004,1111,"Mises (1998, 1)",The Arrow Theorem gave birth to a rich literat...,The Arrow Theorem gave birth to a rich literat...,0,_PVK6Qnz,_xRbChZ3,_8JVpeTd,134,20,...,1.0,1998.0,Unknown Title,10.1515.jeeh-2016-0013.pdf.grobid.tei.xml,267,49,Review of Austrian Economics,44.444444,"['decision-making', 'rules', 'preferences']","['decision-making', 'rules', 'preferences']"

In [25]:
hayek_citations_df = citations_df[citations_df.author == 'Hayek'].sort_values(by='page')

hayek_citations_df.head(10)

,paper_id,raw,sentence,paragraph,co_cited_count,section_id,paragraph_id,sentence_id,sentence_seq_number,reference_seq_number,...,page,year,title,filename,sentence_count,reference_count,source title,similarity,sentence_keywords,paragraph_keywords
208587,2010,"Hayek (1931, chap. 1)","As Hayek (1931, chap. 1) himself emphasized, h...","As Hayek (1931, chap. 1) himself emphasized, h...",0,_A8agYzP,_vuj5DFn,_YkEbteK,55,35,...,1.0,NaN,Suggested Interpretation of the Business-Cycle...,Mr-Hayek-and-the-Classics-A-Suggested-Interpre...,314,53,History of Political Economy,65.408805,['NO-MATCH'],"['hume', 'price', 'money', 'interest', 'prices..."
257529,2612,"(Hayek, 1948, 1-32)","Hayek, more so perhaps than other Austrians, c...",Two worlds collide: A review essay of Humanomi...,0,_MKWNK5S,_C2FsHDj,_N5VBSsC,199,84,...,1.0,1948.0,Two worlds collide: A review essay of Humanomi...,Two-worlds-collide-A-review-essay-of-Humanomic...,325,41,Review of Austrian Economics,100.000000,['hume'],"['humanomics', 'hume', 'ludwig von mises', 'au..."
117921,1123,"Hayek, ""History and Politics"" (1954, pp. 1-2)","-Friedrich Hayek, ""History and Politics"" (1954...","-Friedrich Hayek, ""History and Politics"" (1954...",0,_4RKzd83,_MawJHrN,_7d6bJHd,18,1,...,1.0,1954.0,Accounting is an Evolved Economic Institution *,10.1561.1400000011.pdf.grobid.tei.xml,1937,467,Foundations and Trends in Accounting,97.826087,"['friedrich hayek', 'politics', 'knowledge', '...","['friedrich hayek', 'politics', 'knowledge', '..."
257426,2611,"(Hayek, 1948, 1-32)","Hayek, more so perhaps than other Austrians, c...",Two worlds collide: A review essay of Humanomi...,0,_dSnMdWU,_Y4vE7NZ,_2mZs7UM,199,84,...,1.0,1948.0,Two worlds collide: A review essay of Humanomi...,Two-worlds-collide-A-review-essay-of-Humanomic...,325,41,Review of Austrian Economics,100.000000,['hume'],"['humanomics', 'hume', 'ludwig von mises', 'au..."
132478,1197,"(Hayek, 1948: 1-32;Gamble, 1996;Brown, 2006;Fo...","Indeed, not only is collectivism not normal wi...","Importantly, the condition of the working clas...",3,_W7w3J4K,_cQBHtu2,_akGXdDv,3413,1638,...,1.0,1948.0,THE DARK SIDE OF MANAGEMENT,10.4324.9781315754581.pdf.grobid.tei.xml,3855,337,Knowledge Management and Organizational Learning,76.923077,['NO-MATCH'],"['liberalism', 'transition', 'needs', 'the mar..."
132526,1197,Hayek (1948: 1-32),"Although he (Mayo, 1939: 335) cites Malinowski...",Chapter 4 demonstrated the striking similariti...,1,_v2xv8mV,_9EJ5qFC,_4tVmGqP,3496,1695,...,1.0,1948.0,THE DARK SIDE OF MANAGEMENT,10.4324.9781315754581.pdf.grobid.tei.xml,3855,337,Knowledge Management and Organizational Learning,76.923077,['cooperation'],"['concept', 'the market', 'organization', 'coo..."
132604,1197,Hayek (1948: 1-32),"Along with Hayek (1948: 1-32) and Mayo (1937),...","Along with Hayek (1948: 1-32) and Mayo (1937),...",1,_zRAYbqV,_9tVgmR7,_wvmnsP3,3832,1802,...,1.0,1948.0,THE DARK SIDE OF MANAGEMENT,10.4324.9781315754581.pdf.grobid.tei.xml,3855,337,Knowledge Management and Organizational Learning,76.923077,"['stability', 'capitalism']","['stability', 'capitalism', 'democracy', 'emot..."
200172,1892,"(Hayek 1979, 1)",He has pointed out that we need to distinguish...,The global trend that Fukuyama's account was m...,0,_zcfDmsr,_aPhcQ4k,_97X6mrC,12,2,...,1.0,1979.0,"Liberal constitutionalism, constitutional libe...",Liberal-constitutionalism-constitutional-liber...,291,35,Constitutional Political Economy,100.000000,"['democracy', 'consent']","['sign', 'liberalism', 'the market', 'markets'..."
146852,1288,"Hayek, ""History and Politics"" (1954, pp. 1-2)","-Friedrich Hayek, ""History and Politics"" (1954...","-Friedrich Hayek, ""History and Politics"" (1954...",0,_QVTHtYx,_q6T45j6,_vGSGrm4,16,1,...,1.0,1954.0,Accounting is an Evolved Economic Institution *,Accounting-is-an-evolved-economic-institution_...,62,467,Foundations and Trends in Accounting,97.826087,"['friedrich hayek', 'politics', 'knowledge', '...","['friedrich hayek', 'politics', 'knowledge', '..."
200173,1892,"(Hayek 1973, 1)",While rejecting ''a conception of democracy ac...,The global trend that Fukuyama's account was m...,1,_zcfDmsr,_aPhcQ4k,_qntPFfm,13,3,...,1.0,1973.0,"Liberal constitutionalism, constitutional libe...",Liberal-constitutionalism-constitutional-liber...,291,35,Constitutional Political Economy,100.000000,"['democracy', 'constitution']","['sign', 'liberalism', 'the market', 'markets'..."

In [26]:
mises_citations_df['year'].value_counts()

year
1949.0    1738
1998.0     967
1966.0     915
1996.0     346
1962.0     212
          ...
1917.0       1
2018.0       1
2022.0       1
1994.0       1
1965.0       1
Name: count, Length: 99, dtype: int64

In [27]:
hayek_citations_df['year'].value_counts()

year
1945.0    744
1948.0    417
1952.0    410
1960.0    390
1978.0    246
         ...
2017.0      1
1965.0      1
1927.0      1
1925.0      1
1899.0      1
Name: count, Length: 91, dtype: int64

In [28]:
import math

def map_year_to_book_hayek(year):
    if math.isnan(year):
        return 'unknown-year'
    
    year = int(year)
    if year == 1945:
        return "Use of Knowledge in Society"
    if year == 1948:
        return "Individualism and Economic Order"
    if year == 1952:
        return "The Counter-Evolution of Science"
    if year == 1960:
        return 'The Constitution of Liberty'
    if year == 1978:
        return 'New Studies in Philosophy, Politics, Economics and the History of Ideas'
    if year == 1973:
        return 'Law, Legislation and Liberty – Volume 1: Rules and Order'
    if year == 1967:
        return 'Studies in Philosophy, Politics and Economics'
    if year == 1937:
        return 'Economics and Knowledge'
    
    return "unknown"



# Aplicando ao DataFrame
hayek_citations_df['book'] = hayek_citations_df['year'].apply(map_year_to_book_hayek)

In [29]:
hayek_citations_df[['book', 'year']].value_counts().head(40)

book                                                                     year
Use of Knowledge in Society                                              1945.0    744
Individualism and Economic Order                                         1948.0    417
The Counter-Evolution of Science                                         1952.0    410
The Constitution of Liberty                                              1960.0    390
New Studies in Philosophy, Politics, Economics and the History of Ideas  1978.0    246
Law, Legislation and Liberty – Volume 1: Rules and Order                 1973.0    242
Studies in Philosophy, Politics and Economics                            1967.0    231
Economics and Knowledge                                                  1937.0    196
unknown                                                                  1935.0    184
                                                                         1976.0    173
                                                                         1931.0    166
                                                                         1941.0    152
                                                                         1944.0    148
                                                                         1988.0    146
                                                                         1946.0    139
                                                                         1979.0    122
                                                                         2008.0    105
                                                                         1933.0     94
                                                                         1982.0     72
                                                                         1992.0     72
                                                                         1932.0     57
                                                                         1939.0     56
                                                                         1949.0     53
                                                                         1966.0     52
                                                                         1968.0     50
                                                                         2007.0     49
                                                                         1974.0     47
                                                                         1942.0     44
                                                                         1989.0     42
                                                                         1955.0     40
                                                                         1964.0     36
                                                                         1994.0     36
                                                                         1991.0     36
                                                                         2010.0     34
                                                                         1990.0     31
                                                                         1943.0     29
                                                                         2002.0     29
                                                                         1940.0     28
                                                                         1983.0     28
                                                                         1975.0     27
Name: count, dtype: int64

In [30]:
import pandas as pd

# Lê o arquivo assumindo que é separado por vírgulas
human_action_page_ranges_df = pd.read_csv("chapter-ranges/human-action-page-to-chapter.txt")

human_action_page_ranges_df.head()

   start_page  end_page  chapter
0           0        11        0
1          11        30        1
2          30        72        2
3          72        92        3
4          92        99        4

In [31]:
def get_human_action_chapter_by_page(page):
    row = human_action_page_ranges_df[
        (human_action_page_ranges_df['start_page'] <= page) &
        (human_action_page_ranges_df['end_page'] >= page)
    ]
    if not row.empty:
        return int(row.iloc[0]['chapter'])
    else:
        return "WHOLE"  # ou você pode retornar "Desconhecido", -1, etc.

assert get_human_action_chapter_by_page(111) == 6
assert get_human_action_chapter_by_page(None) == 'WHOLE'

In [32]:
mises_citations_df['human_action_chapter_by_ref_page'] = mises_citations_df['page'].apply(get_human_action_chapter_by_page)
mises_citations_df['human_action_chapter_number'] = mises_citations_df['human_action_chapter_by_ref_page']

In [33]:
chapter_to_part_df = pd.read_csv("chapter-ranges/chapter-to-part.csv")

chapter_to_part_df.head()

,human_action_chapter_number,human_action_chapter_name,human_action_part_number,human_action_part_name
0,WHOLE,WHOLE,WHOLE,WHOLE
1,0,Chapter 0: Introduction,0,Part 0: Introduction
2,1,Chapter 1: Acting Man,1,Part 1: Human Action
3,2,Chapter 2: The Epistemological Problems of the...,1,Part 1: Human Action
4,3,Chapter 3: Economics and the Revolt Against Re...,1,Part 1: Human Action

In [34]:
import pandas as pd

# 🔧 Força os campos de join para string em ambos os DataFrames
mises_citations_df["human_action_chapter_number"] = (
    mises_citations_df["human_action_chapter_number"].astype(str)
)

chapter_to_part_df["human_action_chapter_number"] = (
    chapter_to_part_df["human_action_chapter_number"].astype(str)
)

# 🔗 Join usando merge
mises_citations_df = pd.merge(
    mises_citations_df,
    chapter_to_part_df,
    on="human_action_chapter_number",
    how="left"
)

# ✅ Existem pelo menos 2 valores de part distintos?
assert (
    mises_citations_df["human_action_part_number"]
    .nunique(dropna=True) >= 2
), "human_action_part_number não possui pelo menos dois valores distintos"

In [35]:
mises_citations_df[mises_citations_df.human_action_chapter_number == 'WHOLE'].head()

,paper_id,raw,sentence,paragraph,co_cited_count,section_id,paragraph_id,sentence_id,sentence_seq_number,reference_seq_number,...,reference_count,source title,similarity,sentence_keywords,paragraph_keywords,human_action_chapter_by_ref_page,human_action_chapter_number,human_action_chapter_name,human_action_part_number,human_action_part_name
4677,2641,"Mises (1996, p. 884)","As Mises (1996, p. 884) states, 'To apply the ...","Beyond what has been said, the diversity of en...",0,_vFKWFVS,_XnRFPBN,_wkb2U7y,69,32,...,99,Journal of Philosophical Economics: Reflection...,100.000000,['concept'],"['diversity', 'praxeology', 'economics', 'valu...",WHOLE,WHOLE,WHOLE,WHOLE,WHOLE
4678,927,(Mises [1949] 1966: 884),(Mises [1949] 1966: 884) Examining Rothbard's ...,[E]conomics does not say anything either in fa...,0,_AYtGrJf,_yHKtjZB,_f6G6n6C,157,29,...,16,American Journal of Economics and Sociology,62.040816,"['rothbard', 'value', 'freedom']","['labor', 'credit', 'rothbard', 'economics', '...",WHOLE,WHOLE,WHOLE,WHOLE,WHOLE
4679,760,"(von Mises, 1963, p. 884, emphasis in original)","(von Mises, 1963, p. 884, emphasis in original).",Economics does not assume or postulate that me...,0,_gYvKv4K,_XcTWZtR,_bPTKVT8,104,54,...,144,"Accounting, Auditing and Accountability Journal",100.000000,['von mises'],"['economics', 'human action', 'concept', 'pove...",WHOLE,WHOLE,WHOLE,WHOLE,WHOLE
4680,1916,"(Mises 1966, p. 885)",But if they fail to take the best advantage of...,The body of economic knowledge is an essential...,0,_d8gUVsx,_9SgqNxV,_3M2ZJMN,144,38,...,14,Review of Austrian Economics,44.444444,['economics'],"['knowledge', 'structure', 'civilization', 'ec...",WHOLE,WHOLE,WHOLE,WHOLE,WHOLE
4681,639,"(Mises, 1998a, p. 885)","(Mises, 1998a, p. 885) Mises criticizes the ec...",The body of economic knowledge is an essential...,0,_gr85Qfe,_4VXf7a9,_hAmUGp5,86,20,...,58,Review of Political Economy,80.487805,['beliefs'],"['knowledge', 'structure', 'civilization', 'ec...",WHOLE,WHOLE,WHOLE,WHOLE,WHOLE

In [36]:
# ===== 1. Salvar por sentença =====
mises_citations_df.to_csv("../data/processed/mises_sentence_citations.csv", index=False)
hayek_citations_df.to_csv("../data/processed/hayek_sentence_citations.csv", index=False)


# ===== Função auxiliar: lista única preservando ordem =====
def unique_list(x):
    seen = set()
    result = []
    for item in x:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


# ===== 2. Função para agregação por parágrafo =====
def aggregate_paragraph(df):
    agg_dict = {
        # mantém o parágrafo (único por paragraph_id)
        "paragraph": "first",
        "paragraph_keywords": "first",
        "sentence_keywords": "first",
        
        # mantém sentence_ids únicos
        "sentence_id": unique_list
    }
    
    # adiciona dinamicamente se a coluna existir
    if "human_action_chapter_name" in df.columns:
        agg_dict["human_action_chapter_name"] = unique_list
    if "human_action_chapter_number" in df.columns:
        agg_dict["human_action_chapter_number"] = unique_list
    if "human_action_part_name" in df.columns:
        agg_dict["human_action_part_name"] = unique_list
    if "human_action_part_number" in df.columns:
        agg_dict["human_action_part_number"] = unique_list

    return (
        df
        .sort_values("sentence_seq_number")  # garante ordem correta
        .groupby("paragraph_id")
        .agg(agg_dict)
        .reset_index()
    )


# ===== 3. Aplicar agregação =====
mises_paragraph_df = aggregate_paragraph(mises_citations_df)
mises_paragraph_df.to_csv("../data/processed/mises_paragraph_citations.csv", index=False)


# ===== 4. Salvar por parágrafo =====
hayek_paragraph_df = aggregate_paragraph(hayek_citations_df)
hayek_paragraph_df.to_csv("../data/processed/hayek_paragraph_citations.csv", index=False)

In [37]:
'''
import pandas as pd

# Seleciona apenas o que interessa do mises_refs_df
mises_parts = (
    mises_citations_df[
        ["sentence_id", "author", "human_action_part_number"]
    ]
    .dropna(subset=["sentence_id", "human_action_part_number"])
    .copy()
)

# Faz LEFT JOIN em refs_df
citations_df = citations_df.merge(
    mises_parts,
    on=["sentence_id", "author"],
    how="left"
)


def build_author_node(row):
    if (
        row["author"] == "Mises"
        and pd.notna(row["human_action_part_number"])
    ):
        return f"Mises_{(row['human_action_part_number'])}"
    return row["author"]


citations_df = citations_df.copy()
citations_df["mises_part"] = citations_df.apply(build_author_node, axis=1)

citations_df.to_csv("../data/processed/citations_with_mises_part.csv")

'''

'\nimport pandas as pd\n\n# Seleciona apenas o que interessa do mises_refs_df\nmises_parts = (\n    mises_citations_df[\n        ["sentence_id", "author", "human_action_part_number"]\n    ]\n    .dropna(subset=["sentence_id", "human_action_part_number"])\n    .copy()\n)\n\n# Faz LEFT JOIN em refs_df\ncitations_df = citations_df.merge(\n    mises_parts,\n    on=["sentence_id", "author"],\n    how="left"\n)\n\n\ndef build_author_node(row):\n    if (\n        row["author"] == "Mises"\n        and pd.notna(row["human_action_part_number"])\n    ):\n        return f"Mises_{(row[\'human_action_part_number\'])}"\n    return row["author"]\n\n\ncitations_df = citations_df.copy()\ncitations_df["mises_part"] = citations_df.apply(build_author_node, axis=1)\n\ncitations_df.to_csv("../data/processed/citations_with_mises_part.csv")\n\n'

In [38]:
'''
mises_citations_df.head()
'''

'\nmises_citations_df.head()\n'

In [39]:
mises_citations_df.head()

,paper_id,raw,sentence,paragraph,co_cited_count,section_id,paragraph_id,sentence_id,sentence_seq_number,reference_seq_number,...,reference_count,source title,similarity,sentence_keywords,paragraph_keywords,human_action_chapter_by_ref_page,human_action_chapter_number,human_action_chapter_name,human_action_part_number,human_action_part_name
0,834,"(Mises, 1996(Mises, [1949]], p. 1)",The practitioners of methodological holism are...,One of the defining characteristics of Austria...,0,_4dGvzna,_97b4QYq,_dz5ekbM,96,47,...,43,Advances in Austrian Economics,100.000000,['NO-MATCH'],"['austrian', 'economics', 'methodological indi...",0,0,Chapter 0: Introduction,0,Part 0: Introduction
1,1842,"(Mises 2011, 1)","Interventionism, for its part, ""seeks to retai...",Consider Mises's own definitions of capitalism...,0,_yCU3SGE,_h8VDttU,_5k2NTcp,352,148,...,87,Quarterly Journal of Austrian Economics,100.000000,"['interventionism', 'private property', 'produ...","['capitalism', 'socialism', 'interventionism',...",0,0,Chapter 0: Introduction,0,Part 0: Introduction
2,1197,Mises (1944: 1-19),"Indeed, Mises (1944: 1-19) explicitly cites th...",Democracy was dangerous because it enabled the...,0,_ThHCvKg,_xKvBxdX,_EndqMMB,3399,1633,...,337,Knowledge Management and Organizational Learning,76.923077,['NO-MATCH'],"['democracy', 'economy', 'neo-liberalism', 'th...",0,0,Chapter 0: Introduction,0,Part 0: Introduction
3,1197,"Mises, 1944: 1-19)","(Lippmann, 1938(Lippmann, /1943: 263;: 263; em...",The kind of self-education which a self-govern...,3,_W7w3J4K,_FXcX2C6,_mpaD3bx,3456,1675,...,337,Knowledge Management and Organizational Learning,76.923077,['NO-MATCH'],"['education', 'words', 'democracy', 'discovery...",0,0,Chapter 0: Introduction,0,Part 0: Introduction
4,1920,"Mises's (1962, 1)","Indeed, the logical structure of the human min...","That is to say, Mises believes that I can gras...",0,_JRV4vR4,_K4EEPwH,_kzagVzN,367,282,...,66,Review of Austrian Economics,100.000000,"['structure', 'epistemology', 'knowledge', 'po...","['action', 'structure', 'epistemology', 'knowl...",0,0,Chapter 0: Introduction,0,Part 0: Introduction

In [40]:
import pandas as pd

reduced_mises_citations_df = mises_citations_df[['author','section_id', 'paragraph_id', 'sentence_id',
                                                  'page', 'human_action_chapter_number', 'human_action_part_number',
                                                  'sentence']]

# LEFT JOIN invertido: Mises como base
citations_joined_df = (
    reduced_mises_citations_df
    .merge(
        citations_df[['author', 'section_id', 'paragraph_id', 'sentence_id', 'sentence']],
        on="section_id",
        how="left",
        suffixes=("_mises_citation", "_citation")
    )
)

# =========================
# Ordenação das colunas
# =========================

cols = list(citations_joined_df.columns)

# Colunas base (sem sufixo)
base_cols = [
    c for c in cols
    if not c.endswith(("_mises_citation", "_citation"))
]

# =========================
# (Opcional) Exportar CSV
# =========================
citations_joined_df.to_csv("../data/processed/mises_co_citations_per_paragraph.csv", index=False)